lib: [
  "_build/install/default/lib/propa/META"
  "_build/install/default/lib/propa/dune-package"
  "_build/install/default/lib/propa/main.ml"
  "_build/install/default/lib/propa/opam"
  "_build/install/default/lib/propa/propa.a"
  "_build/install/default/lib/propa/propa.cma"
  "_build/install/default/lib/propa/propa.cmi"
  "_build/install/default/lib/propa/propa.cmt"
  "_build/install/default/lib/propa/propa.cmx"
  "_build/install/default/lib/propa/propa.cmxa"
  "_build/install/default/lib/propa/propa.ml"
  "_build/install/default/lib/propa/propa__Main.cmi"
  "_build/install/default/lib/propa/propa__Main.cmt"
  "_build/install/default/lib/propa/propa__Main.cmx"
]
libexec: [
  "_build/install/default/lib/propa/propa.cmxs"
]
